#ifndef _WIN_API_DEFINE_
#define _WIN_API_DEFINE_

#include "WinApiTypes.mqh"

#define WEB_SOCKET_HANDLE HANDLE

enum WEB_SOCKET_PROPERTY_TYPE {
  WEB_SOCKET_RECEIVE_BUFFER_SIZE_PROPERTY_TYPE,
  WEB_SOCKET_SEND_BUFFER_SIZE_PROPERTY_TYPE,
  WEB_SOCKET_DISABLE_MASKING_PROPERTY_TYPE,
  WEB_SOCKET_ALLOCATED_BUFFER_PROPERTY_TYPE,
  WEB_SOCKET_DISABLE_UTF8_VERIFICATION_PROPERTY_TYPE,
  WEB_SOCKET_KEEPALIVE_INTERVAL_PROPERTY_TYPE,
  WEB_SOCKET_SUPPORTED_VERSIONS_PROPERTY_TYPE
};

struct WEB_SOCKET_PROPERTY{
  WEB_SOCKET_PROPERTY_TYPE Type;
  uint                     pvValue[];
  ULONG                    ulValueSize;
};

#endif